version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"           # chemin vers ton requirements.txt
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "some-package-to-ignore"
        versions: ["<2.0.0"]
