name: Docker Build & Scan & Push

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/task-manager
      TAG: ${{ github.sha }}

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:$TAG \
            -f backend/Dockerfile \
            .

      # 5. Scan image with Trivy
      - name: Scan Docker image with Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.68.2/trivy_0.68.2_Linux-64bit.deb
          sudo apt install -y ./trivy_0.68.2_Linux-64bit.deb
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME:$TAG

      # 6. Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$TAG
